site_name: Sane-Figs
site_url: https://jeandavidt.github.io/sane-figs/
repo_url: https://github.com/jeandavidt/sane-figs

docs_dir: docs_source
site_dir: site

nav:
  - Home: index.md
  - Presets: presets.md
  - Colorways: colorways.md
  - Watermarks: watermarks.md
  - Interactive Demo: interactive_demo.html
  - Size Comparison tool: size_comparison_demo.html
  - Libraries:
    - Matplotlib: libraries/matplotlib.md
    - Seaborn: libraries/seaborn.md
    - Plotly: libraries/plotly.md
    - Altair: libraries/altair.md

theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

hooks:
  - hooks/__init__.py
